name: corbanmailloux
markdown: redcarpet
highlighter: pygments
encoding: UTF-8
permalink: pretty # to remove the ".html" extension when serving file

url: https://corb.co
title: corb.co
description: "A personal and projects webpage for Corban Mailloux."

# Owner/author information
owner:
    full-name: "Corban Mailloux"

gems:
  - jekyll-sitemap

# Limit what is hosted on the site.
exclude: 
  - "runServer.bat"
  - "CNAME"
  - "corbanmailloux.github.io Project.sublime-project"
  - "corbanmailloux.github.io Project.sublime-workspace"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"


collections:
  projects:
    output: true
    permalink: /projects/:path/
  projectgroups:
    output: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "projects"
    values:
      layout: "project"
      group: "uncategorized"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "projectgroups"
    values:
      weight: 10
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
