name: corbanmailloux
markdown: redcarpet
highlighter: rouge
encoding: UTF-8
permalink: pretty # to remove the ".html" extension when serving file

url: https://corb.co
title: Corban Mailloux
description: "A personal and projects webpage for Corban Mailloux."

# Owner/author information
owner:
    full-name: "Corban Mailloux"

plugins:
  - jekyll-sitemap

# Limit what is hosted on the site.
exclude:
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"

include:
  - ".well-known"

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "projects"
    values:
      layout: "project"
